<!DOCTYPE html><html lang="en-us" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  
  
  
  <meta name="generator" content="Wowchemy 5.0.0-beta.1 for Hugo">
  

  

  
  

  
  
  
  
  
    
    
    
  
  

  

  
  
  
    
  
  <meta name="description" content="Data Manipulation">

  
  <link rel="alternate" hreflang="en-us" href="https://psqf6250.brandonlebeau.org/rcode/data_munging/">

  







  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  

  
  
  
  <meta name="theme-color" content="#1565c0">
  

  
  

  
  
  
  
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous" media="print" onload="this.media='all'">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/github.min.css" crossorigin="anonymous" title="hl-light" media="print" onload="this.media='all'">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" media="print" onload="this.media='all'" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.css" integrity="sha512-1xoFisiGdy9nvho8EgXuXvnpR5GAMSjFwp40gSRE3NwdUdIMIKuPa7bqoUhLD0O/5tPNhteAsE5XyyMi5reQVA==" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.2.2/lazysizes.min.js" integrity="sha512-TmDwFLhg3UA4ZG0Eb4MIyT1O1Mb+Oww5kFG0uHqXsdbyZz9DcvYQhKpGgNkamAI6h2lGGZq2X8ftOJvF/XjTUg==" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      
        
      

      
    
      

      
      

      
    
      

      
      

      
    

  

  
  
  
    
      
      <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap" media="print" onload="this.media='all'">
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.2a5f61e11ca83c1781264fc4703f4117.css">

  




  

  


  
  

  

  
  <link rel="manifest" href="/index.webmanifest">
  

  <link rel="icon" type="image/png" href="/images/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_32x32_fill_lanczos_center_2.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_192x192_fill_lanczos_center_2.png">

  <link rel="canonical" href="https://psqf6250.brandonlebeau.org/rcode/data_munging/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="og:site_name" content="PSQF 6250">
  <meta property="og:url" content="https://psqf6250.brandonlebeau.org/rcode/data_munging/">
  <meta property="og:title" content="Data Manipulation | PSQF 6250">
  <meta property="og:description" content="Data Manipulation"><meta property="og:image" content="https://psqf6250.brandonlebeau.org/media/blue-balloon.jpg">
  <meta property="twitter:image" content="https://psqf6250.brandonlebeau.org/media/blue-balloon.jpg"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2021-02-08T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2021-02-08T00:00:00&#43;00:00">
  

  



  


  


  





  <title>Data Manipulation | PSQF 6250</title>

</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper  ">

  
  
  
  
  
  
  
  
  <script src="/js/wowchemy-init.min.7de282f2047be3c570af3a58788341e7.js"></script>

  

<aside class="search-modal" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#" aria-label="Close"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control"
        aria-label="Search...">
        
      </div>

      

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>



  <div class="page-header">
    












<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">PSQF 6250</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">PSQF 6250</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#logistics"><span>Logistics</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/syllabus/"><span>Syllabus</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/schedule/"><span>Schedule</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/content/"><span>Content</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link  active" href="/rcode/"><span>R Code</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/assignments/"><span>Assignments</span></a>
        </li>

        
        

        

        
        
        
          
        

        

        
        
        
        

        
          
            
            
          
          
            
            
            
              
            
            
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#people"><span>People</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      
        
      

      
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-label="Display preferences">
          <i class="fas fa-moon" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>


  </div>

  <div class="page-body">
    





<div class="container-fluid docs">
  <div class="row flex-xl-nowrap">
    <div class="col-12 col-md-3 col-xl-2 docs-sidebar">
      <form class="docs-search d-flex align-items-center">
  <button class="btn docs-toggle d-md-none p-0 mr-3" type="button" data-toggle="collapse" data-target="#docs-nav" aria-controls="docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
    <span><i class="fas fa-bars"></i></span>
  </button>

  
  <button class="form-control sidebar-search js-search">
    <i class="fas fa-search pr-2"></i>
    <span class="sidebar-search-text">Search...</span>
    <span class="sidebar-search-shortcut">/</span>
  </button>
  
</form>

<nav class="collapse docs-links" id="docs-nav">
  
  
  
  
  
  

  
  
    

    
      

      
      
      


  
    
    
    
    
      
    
    

    
      <ul class="nav docs-sidenav">
        <li class=""><a href="/rcode/">R Syntax</a></li>
    
      


  <li class=""><a href="/rcode/graphics/">Graphics</a></li>



  <li class=""><a href="/rcode/r-basics/">R Basics</a></li>



  <li class=""><a href="/rcode/ggplot2_extensions/">ggplot2 extensions</a></li>



  <li class=""><a href="/rcode/graphics-tips/">Graphics Tips</a></li>



  <li class="active"><a href="/rcode/data_munging/">Data Manipulation</a></li>



  <li class=""><a href="/rcode/r_scripts/">R Scripts</a></li>



  <li class=""><a href="/rcode/eda/">Exploratory Data Analysis</a></li>



  <li class=""><a href="/rcode/projects/">R Projects -  RStudio</a></li>



  <li class=""><a href="/rcode/data_import/">Data Import</a></li>



  <li class=""><a href="/rcode/data_restructuring/">Data Restructuring</a></li>



  <li class=""><a href="/rcode/data_joins/">Joining Data</a></li>



  <li class=""><a href="/rcode/factors/">Factors</a></li>



  <li class=""><a href="/rcode/strings/">Working with Character Strings</a></li>



  <li class=""><a href="/rcode/model-intro/">Model Introduction</a></li>



  <li class=""><a href="/rcode/model-part2/">Building Upon Linear Models</a></li>



  <li class=""><a href="/rcode/adv-model/">Advanced Modeling Topics</a></li>

      
    

    
      </ul>
    

  
</nav>

    </div>

    
    
    <div class="d-none d-xl-block col-xl-2 docs-toc">
      <ul class="nav toc-top">
        <li><a href="#" id="back_to_top" class="docs-toc-title">Contents</a></li>
      </ul>

      

      
    </div>
    

    <main class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 docs-content" role="main">

      <article class="article">

        <div class="docs-article-container">
          

          <h1>Data Manipulation</h1>

          <div class="article-style">
            
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>

<div id="TOC">

</div>

<p>Data munging (i.e. data transformations, variable creation, filtering) is a common task that is often overlooked in traditional statistics textbooks and courses. Even though it is omitted, the task of cleaning and organizing the data (coming in week 5 of the course)</p>
<p>Data from the <code>fivethirtyeight</code> package is used in this set of notes to show the use of the <code>dplyr</code> verbs for data munging. This package can be installed with the following command:</p>
<pre class="r"><code>install.packages(&quot;fivethirtyeight&quot;)</code></pre>
<p>To get started with this set of notes, you will need the following packages loaded:</p>
<pre class="r"><code>library(fivethirtyeight)
library(tidyverse)</code></pre>
<p>We are going to explore the <code>congress_age</code> data set in more detail. Take a few minutes to familiarize yourself with the data.</p>
<pre class="r"><code>View(congress_age)
?congress_age</code></pre>
<pre class="r"><code>congress_age</code></pre>
<pre><code>## # A tibble: 18,635 x 13
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph    Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert    Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph    Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles   Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William   &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James     A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard   Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol       &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin    &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles   Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 18,625 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<div id="using-dplyr-for-data-munging" class="section level2">
<h2>Using <code>dplyr</code> for data munging</h2>
<p>The <code>dplyr</code> package uses verbs for common data manipulation tasks. These include:</p>
<ul>
<li><code>filter()</code></li>
<li><code>arrange()</code></li>
<li><code>select()</code></li>
<li><code>mutate()</code></li>
<li><code>summarise()</code></li>
</ul>
<p>The great aspect of these verbs are that they all take a similar data structure, the first argument is always the data, the other arguments are unquoted column names. These functions also always return a data frame in which the rows are observations and the columns are variables.</p>
</div>
<div id="examples-with-filter" class="section level2">
<h2>Examples with <code>filter()</code></h2>
<p>The <code>filter</code> function selects rows that match a specified condition(s). For example, suppose we wanted to select only the rows in the data that are a part of the 80th congress. The following code will do this action:</p>
<pre class="r"><code>filter(congress_age, congress == 80)</code></pre>
<pre><code>## # A tibble: 555 x 13
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph    Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert    Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph    Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles   Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William   &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James     A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard   Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol       &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin    &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles   Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 545 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<p>Notice from above two things, first, the function returned a new data frame. Therefore, if this subsetted data is to be saved, we need to save it to an object, for example, as follows:</p>
<pre class="r"><code>congress_80 &lt;- filter(congress_age, congress == 80)</code></pre>
<p>Notice now that the data were not automatically printed, instead it was saved into the object called <code>congress_80</code>. If you wish to preview the data and save it to an object in a single step, you need to wrap the command above in parentheses. Take a second to try this yourself.</p>
<p>Secondly, notice from the above commands that equality in R is done with <code>==</code> not just a single <code>=</code>. The single <code>=</code> is used for named arguments, therefore when testing for equality you need to be sure to use <code>==</code>, this is a common frustration and source of bugs when getting started with R.</p>
<p>Selecting values based on a character vector are similar to numeric values. For example, suppose we wanted to select only those rows pertaining to those from the senate. The following code will do that:</p>
<pre class="r"><code>senate &lt;- filter(congress_age, chamber == &#39;senate&#39;)</code></pre>
<div id="combining-logical-operations" class="section level3">
<h3>Combining Logical Operations</h3>
<p>The <code>filter</code> function becomes much more useful with more complex operations. For example, suppose we were interested in selecting the rows that belong to the 80th senate.</p>
<pre class="r"><code>filter(congress_age, congress == 80, chamber == &#39;senate&#39;)</code></pre>
<pre><code>## # A tibble: 102 x 13
##    congress chamber bioguide firstname middlename lastname suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;date&gt;    
##  1       80 senate  C000133  Arthur    &lt;NA&gt;       Capper   &lt;NA&gt;   1865-07-14
##  2       80 senate  G000418  Theodore  Francis    Green    &lt;NA&gt;   1867-10-02
##  3       80 senate  M000499  Kenneth   Douglas    McKellar &lt;NA&gt;   1869-01-29
##  4       80 senate  R000112  Clyde     Martin     Reed     &lt;NA&gt;   1871-10-19
##  5       80 senate  M000895  Edward    Hall       Moore    &lt;NA&gt;   1871-11-19
##  6       80 senate  O000146  John      Holmes     Overton  &lt;NA&gt;   1875-09-17
##  7       80 senate  M001108  James     Edward     Murray   &lt;NA&gt;   1876-05-03
##  8       80 senate  M000308  Patrick   Anthony    McCarran &lt;NA&gt;   1876-08-08
##  9       80 senate  T000165  Elmer     &lt;NA&gt;       Thomas   &lt;NA&gt;   1876-09-08
## 10       80 senate  W000021  Robert    Ferdinand  Wagner   &lt;NA&gt;   1877-06-08
## # … with 92 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<p>By default, the <code>filter</code> function uses AND when combining multiple arguments. Therefore, the above command returned only the 102 rows belonging to senators from the 80th congress. The figure on <a href="https://r4ds.had.co.nz/transform.html#logical-operators">section 5.2.2</a> of R for Data Science shows all the possible boolean operators.</p>
<p>Using an example of the OR operator using <code>|</code> to select the 80th and 81st congress:</p>
<pre class="r"><code>filter(congress_age, congress == 80 | congress == 81)</code></pre>
<pre><code>## # A tibble: 1,112 x 13
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph    Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert    Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph    Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles   Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William   &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James     A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard   Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol       &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin    &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles   Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 1,102 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<p>Note that to do the OR operator, you need to name the variable twice. When selecting multiple values in the same variable, a handy shortcut is <code>%in%</code>. The same command can be run with the following shorthand: handy shortcut is <code>%in%</code>. The same command can be run with the following shorthard</p>
<pre class="r"><code>filter(congress_age, congress %in% c(80, 81))</code></pre>
<pre><code>## # A tibble: 1,112 x 13
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph    Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert    Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph    Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles   Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William   &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James     A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard   Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol       &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin    &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles   Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 1,102 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
</div>
<div id="not-operator" class="section level3">
<h3>Not Operator</h3>
<p>Another useful operator that deserves a bit more discussion is the not operator, <code>!</code>. For example, suppose we wanted to omit the 80th congress:</p>
<pre class="r"><code>filter(congress_age, congress != 80)</code></pre>
<pre><code>## # A tibble: 18,080 x 13
##    congress chamber bioguide firstname middlename lastname suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;date&gt;    
##  1       81 house   D000448  Robert    Lee        Doughton &lt;NA&gt;   1863-11-07
##  2       81 house   S000001  Adolph    Joachim    Sabath   &lt;NA&gt;   1866-04-04
##  3       81 house   E000023  Charles   Aubrey     Eaton    &lt;NA&gt;   1868-03-29
##  4       81 house   W000265  Richard   Joseph     Welch    &lt;NA&gt;   1869-02-13
##  5       81 house   B000565  Sol       &lt;NA&gt;       Bloom    &lt;NA&gt;   1870-03-09
##  6       81 house   H000943  Merlin    &lt;NA&gt;       Hull     &lt;NA&gt;   1870-12-18
##  7       81 house   B000545  Schuyler  Otis       Bland    &lt;NA&gt;   1872-05-04
##  8       81 house   K000138  John      Hosea      Kerr     &lt;NA&gt;   1873-12-31
##  9       81 house   C000932  Robert    &lt;NA&gt;       Crosser  &lt;NA&gt;   1874-06-07
## 10       81 house   K000039  John      &lt;NA&gt;       Kee      &lt;NA&gt;   1874-08-22
## # … with 18,070 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<p>It is also possible to do not with an AND operator as follows:</p>
<pre class="r"><code>filter(congress_age, congress == 80 &amp; !chamber == &#39;senate&#39;)</code></pre>
<pre><code>## # A tibble: 453 x 13
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph    Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert    Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph    Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles   Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William   &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James     A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard   Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol       &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin    &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles   Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 443 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<div id="exercises" class="section level4">
<h4>Exercises</h4>
<ol style="list-style-type: decimal">
<li>Using the congress data, select the rows belonging to the democrats (party = D) from the senate of the 100th congress.</li>
<li>Select all congress members who are older than 80 years old.</li>
</ol>
</div>
</div>
<div id="note-on-missing-data" class="section level3">
<h3>Note on Missing Data</h3>
<p>Missing data within R are represented with <code>NA</code> which stands for not available.</p>
<p>There are no missing data in the congress data, however, by default the <code>filter</code> function will not return any missing values. In order to select missing data, you need to use the <code>is.na</code> function.</p>
<div id="exercise" class="section level4">
<h4>Exercise</h4>
<ol style="list-style-type: decimal">
<li>Given the following simple vector, run one filter that selects all values greater than 100. Write a second filter command that selects all the rows greater than 100 and also the NA value.</li>
</ol>
<pre class="r"><code>df &lt;- tibble(x = c(200, 30, NA, 45, 212))</code></pre>
</div>
</div>
</div>
<div id="examples-with-arrange" class="section level2">
<h2>Examples with <code>arrange()</code></h2>
<p>The <code>arrange</code> function is used for ordering rows in the data. For example, suppose we wanted to order the rows in the congress data by the state the members of congress lived in. This can be done using the <code>arrange</code> function as follows:</p>
<pre class="r"><code>arrange(congress_age, state)</code></pre>
<pre><code>## # A tibble: 18,635 x 13
##    congress chamber bioguide firstname middlename lastname suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  2       81 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  3       82 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  4       83 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  5       84 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  6       85 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  7       86 house   R000282  Ralph     Julian     Rivers   &lt;NA&gt;   1903-05-23
##  8       86 senate  G000508  Ernest    &lt;NA&gt;       Gruening &lt;NA&gt;   1887-02-06
##  9       86 senate  B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
## 10       87 house   R000282  Ralph     Julian     Rivers   &lt;NA&gt;   1903-05-23
## # … with 18,625 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<p>Similar to the filter function, additional arguments can be added to add more layers to the ordering. For example, if we were interested in ordering the rows by state and then by party affiliation.</p>
<pre class="r"><code>arrange(congress_age, state, party)</code></pre>
<pre><code>## # A tibble: 18,635 x 13
##    congress chamber bioguide firstname middlename lastname suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  2       81 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  3       82 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  4       83 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  5       84 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  6       85 house   B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
##  7       86 house   R000282  Ralph     Julian     Rivers   &lt;NA&gt;   1903-05-23
##  8       86 senate  G000508  Ernest    &lt;NA&gt;       Gruening &lt;NA&gt;   1887-02-06
##  9       86 senate  B000201  Edward    Lewis      Bartlett &lt;NA&gt;   1904-04-20
## 10       87 house   R000282  Ralph     Julian     Rivers   &lt;NA&gt;   1903-05-23
## # … with 18,625 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<p>More variables can easily be added to the <code>arrange</code> function. Notice from the above two commands that the ordering of the rows is in ascending order, if descending order is desired, the <code>desc</code> function. For example, to order the data starting with the latest congress first:</p>
<pre class="r"><code>arrange(congress_age, desc(congress))</code></pre>
<pre><code>## # A tibble: 18,635 x 13
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1      113 house   H000067  Ralph     M.         Hall      &lt;NA&gt;   1923-05-03
##  2      113 house   D000355  John      D.         Dingell   &lt;NA&gt;   1926-07-08
##  3      113 house   C000714  John      &lt;NA&gt;       Conyers   Jr.    1929-05-16
##  4      113 house   S000480  Louise    McIntosh   Slaughter &lt;NA&gt;   1929-08-14
##  5      113 house   R000053  Charles   B.         Rangel    &lt;NA&gt;   1930-06-11
##  6      113 house   J000174  Sam       Robert     Johnson   &lt;NA&gt;   1930-10-11
##  7      113 house   Y000031  C.        W. Bill    Young     &lt;NA&gt;   1930-12-16
##  8      113 house   C000556  Howard    &lt;NA&gt;       Coble     &lt;NA&gt;   1931-03-18
##  9      113 house   L000263  Sander    M.         Levin     &lt;NA&gt;   1931-09-06
## 10      113 house   Y000033  Don       E.         Young     &lt;NA&gt;   1933-06-09
## # … with 18,625 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
</div>
<div id="examples-with-select" class="section level2">
<h2>Examples with <code>select()</code></h2>
<p>The <code>select</code> function is used to select columns (i.e. variables) from the data but keep all the rows. For example, maybe we only needed the congress number, the chamber, the party affiliation, and the age of the members of congress. We can reduce the data to just these variables using <code>select</code>.</p>
<pre class="r"><code>select(congress_age, congress, chamber, party, age)</code></pre>
<pre><code>## # A tibble: 18,635 x 4
##    congress chamber party   age
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;dbl&gt;
##  1       80 house   D      85.9
##  2       80 house   D      83.2
##  3       80 house   D      80.7
##  4       80 house   R      78.8
##  5       80 house   R      78.3
##  6       80 house   R      78  
##  7       80 house   R      77.9
##  8       80 house   D      76.8
##  9       80 house   R      76  
## 10       80 house   R      75.8
## # … with 18,625 more rows</code></pre>
<p>Similar to the <code>arrange</code> functions, the variables that you wish to keep are separated by commas and come after the data argument.</p>
<p>For more complex selection, the <code>dplyr</code> package has additional functions that are helpful for variable selection. These include:
- <code>starts_with()</code>
- <code>ends_with()</code>
- <code>contains()</code>
- <code>matches()</code>
- <code>num_range()</code></p>
<p>These helper functions can be useful for selecting many variables that match a specific pattern. For example, suppose we were interested in selecting all the name variables, this can be accomplished using the <code>contains</code> function as follows:</p>
<pre class="r"><code>select(congress_age, contains(&#39;name&#39;))</code></pre>
<pre><code>## # A tibble: 18,635 x 3
##    firstname middlename lastname 
##    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;    
##  1 Joseph    Jefferson  Mansfield
##  2 Robert    Lee        Doughton 
##  3 Adolph    Joachim    Sabath   
##  4 Charles   Aubrey     Eaton    
##  5 William   &lt;NA&gt;       Lewis    
##  6 James     A.         Gallagher
##  7 Richard   Joseph     Welch    
##  8 Sol       &lt;NA&gt;       Bloom    
##  9 Merlin    &lt;NA&gt;       Hull     
## 10 Charles   Laceille   Gifford  
## # … with 18,625 more rows</code></pre>
<p>Another useful shorthand to select multiple columns in succession is the <code>:</code> operator. For example, suppose we wanted to select all the variables between congress and bithday.</p>
<pre class="r"><code>select(congress_age, congress:birthday)</code></pre>
<pre><code>## # A tibble: 18,635 x 8
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph    Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert    Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph    Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles   Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William   &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James     A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard   Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol       &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin    &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles   Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 18,625 more rows</code></pre>
<div id="rename-variables" class="section level3">
<h3>Rename variables</h3>
<p>The select function does allow you to rename variables, however, using the select function to rename variables is not usually advised as you may end up missing a variable that you wish to keep during the renaming operation. Instead, using the <code>rename</code> function is better practice.</p>
<pre class="r"><code>rename(congress_age, first_name = firstname, last_name = lastname)</code></pre>
<pre><code>## # A tibble: 18,635 x 13
##    congress chamber bioguide first_name middlename last_name suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph     Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert     Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph     Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles    Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William    &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James      A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard    Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol        &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin     &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles    Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 18,625 more rows, and 5 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;</code></pre>
<p>By default, the rename function will not save changes to the object, if you wish to save the name differences (very likely), be sure to save this new step to an object.</p>
<div id="exercises-1" class="section level4">
<h4>Exercises</h4>
<ol style="list-style-type: decimal">
<li>Using the <code>dplyr</code> helper functions, select all the variables that start with the letter ‘c’.</li>
<li>Rename the first three variables in the congress data to ‘x1’, ‘x2’, ‘x3’.</li>
<li>After renaming the first three variables, use this new data (ensure you saved the previous step to an object) to select these three variables with the <code>num_range</code> function.</li>
</ol>
</div>
</div>
</div>
<div id="examples-with-mutate" class="section level2">
<h2>Examples with <code>mutate()</code></h2>
<p><code>mutate</code> is a useful verb that allows you to add new columns to the existing data set. Actions done with <code>mutate</code> include adding a column of means, counts, or other transformations of existing variables. Suppose for example, we wished to convert the party affiliation of the members of congress into a dummy (indicator) variable. This may be useful to more easily compute a proportion or count for instance.</p>
<p>This can be done with the <code>mutate</code> function. Below, I’m first going to use <code>select</code> to reduce the number of columns to make it easier to see the operation.</p>
<pre class="r"><code>congress_red &lt;- select(congress_age, congress, chamber, state, party)

mutate(congress_red, 
       democrat = ifelse(party == &#39;D&#39;, 1, 0),
       num_democrat = sum(democrat)
       )</code></pre>
<pre><code>## # A tibble: 18,635 x 6
##    congress chamber state party democrat num_democrat
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;        &lt;dbl&gt;
##  1       80 house   TX    D            1        10290
##  2       80 house   NC    D            1        10290
##  3       80 house   IL    D            1        10290
##  4       80 house   NJ    R            0        10290
##  5       80 house   KY    R            0        10290
##  6       80 house   PA    R            0        10290
##  7       80 house   CA    R            0        10290
##  8       80 house   NY    D            1        10290
##  9       80 house   WI    R            0        10290
## 10       80 house   MA    R            0        10290
## # … with 18,625 more rows</code></pre>
<p>You’ll notice that the number of rows in the data are the same (18635) as it was previously, but now the two new columns have been added to the data. One converted the party affiliation to a series of 0/1 values and the other variable counted up the number of democrats elected since the 80th congress. Notice how this last variable is simply repeated for all values in the data. The operation done here is not too exciting, however, we will learn another utility later that allows us to group the data to calculate different values for each group.</p>
<p>Lastly, from the output above, notice that I was able to reference a variable that I created previously in the mutate command. This is unique to the <code>dplyr</code> package and allows you to create a single <code>mutate</code> command to add many variables, even those that depend on prior calculations. Obviously, if you need to reference a calculation in another calculation, they need to be done in the proper order.</p>
<div id="creation-functions" class="section level3">
<h3>Creation Functions</h3>
<p>There are many useful operators to use when creating additional variables. The R for Data Science text has many examples shown in <a href="http://r4ds.had.co.nz/transform.html">section 5.5.1</a>. In general useful operators include addition, subtraction, multiplication, division, descriptive statistics (we will talk more about these in week 4), ranks, logical comparisons, and many more. The exercises will have you explore some of these operations in more detail.</p>
<div id="exercises-2" class="section level4">
<h4>Exercises</h4>
<ol style="list-style-type: decimal">
<li>Using the <code>diamonds</code> data, use <code>?diamonds</code> for more information on the data, use the <code>mutate</code> function to calculate the price per carat. Hint, this operation would involve standardizing the price variable so that all are comparable at 1 carat.</li>
<li>Calculate the rank of the original price variable and the new price variable calculated above using the <code>min_rank</code> function. Are there differences in the ranking of the prices? Hint, it may be useful to test if the two ranks are equal to explore this.</li>
</ol>
</div>
</div>
</div>
<div id="examples-with-summarise" class="section level2">
<h2>Examples with <code>summarise()</code></h2>
<p><code>summarise</code> is very similar to the <code>mutate</code> function, except instead of adding additional columns to the data, it collapses data down to a single row. For instance, doing the same operation as the example with <code>mutate</code> above:</p>
<pre class="r"><code>congress_2 &lt;- mutate(congress_age, 
       democrat = ifelse(party == &#39;D&#39;, 1, 0)
       )

summarise(congress_2, 
          num_democrat = sum(democrat)
          )</code></pre>
<pre><code>## # A tibble: 1 x 1
##   num_democrat
##          &lt;dbl&gt;
## 1        10290</code></pre>
<p>Notice now, instead of repeating the same value for all the rows as with <code>mutate</code>, <code>summarise</code> collapsed the data into a single numeric summary. Normally this is not a very interesting data activity, however, used in tandem with another function, <code>group_by</code>, interesting summary statistics can be calculated.</p>
<p>Suppose we were interested in calculating the number of democrats in each congress. This can be achieved with similar code to above, but first by grouping the data as follows:</p>
<pre class="r"><code>congress_grp &lt;- group_by(congress_2, congress)

summarise(congress_grp, 
          num_democrat = sum(democrat),
          total = n(),
          prop_democrat = num_democrat / total
)</code></pre>
<pre><code>## # A tibble: 34 x 4
##    congress num_democrat total prop_democrat
##  *    &lt;int&gt;        &lt;dbl&gt; &lt;int&gt;         &lt;dbl&gt;
##  1       80          247   555         0.445
##  2       81          330   557         0.592
##  3       82          292   555         0.526
##  4       83          274   557         0.492
##  5       84          288   544         0.529
##  6       85          295   547         0.539
##  7       86          356   554         0.643
##  8       87          339   559         0.606
##  9       88          332   552         0.601
## 10       89          371   548         0.677
## # … with 24 more rows</code></pre>
<p>Notice above, the use of the <code>group_by</code> function to group the data first by congress. Then this new grouped data is passed to the <code>summarise</code> command. As you can see from the output, the operations performed with the <code>summarise</code> function are done for each unique level of the congress variable. You could now easily plot these to see the trend in proportion of democrats has changed over time.</p>
<pre class="r"><code>library(ggplot2)
num_dem &lt;- summarise(congress_grp, 
                     num_democrat = sum(democrat),
                     total = n(),
                     prop_democrat = num_democrat / total
)
ggplot(num_dem, aes(x = congress, y = prop_democrat)) + 
  geom_line()</code></pre>
<p><img src="/rcode/data_munging_files/figure-html/trend-1.png" width="672" /></p>
<div id="exercises-3" class="section level4">
<h4>Exercises</h4>
<ol style="list-style-type: decimal">
<li>Suppose we wanted to calculate the number and proportion of republicans instead of democrats, assuming these are the only two parties, edit the <code>summarise</code> command above to calculate these values.</li>
<li>Suppose instead of using <code>sum(democrat)</code> above, we used <code>mean(democrat)</code>, what does this value return? Why does it return this value?</li>
</ol>
</div>
<div id="extending-group_by-in-other-places" class="section level3">
<h3>Extending <code>group_by()</code> in other places</h3>
<p>The <code>group_by</code> function is also useful with the <code>mutate</code> function and works in a similar way as <code>summarise</code> above. For example, if we wanted to keep the values calculated above in the original data, we could use <code>mutate</code> instead of <code>summarise</code>. This would look like the following:</p>
<pre class="r"><code>mutate(congress_grp, 
       num_democrat = sum(democrat),
       total = n(),
       prop_democrat = num_democrat / total
)</code></pre>
<pre><code>## # A tibble: 18,635 x 17
## # Groups:   congress [34]
##    congress chamber bioguide firstname middlename lastname  suffix birthday  
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;  &lt;date&gt;    
##  1       80 house   M000112  Joseph    Jefferson  Mansfield &lt;NA&gt;   1861-02-09
##  2       80 house   D000448  Robert    Lee        Doughton  &lt;NA&gt;   1863-11-07
##  3       80 house   S000001  Adolph    Joachim    Sabath    &lt;NA&gt;   1866-04-04
##  4       80 house   E000023  Charles   Aubrey     Eaton     &lt;NA&gt;   1868-03-29
##  5       80 house   L000296  William   &lt;NA&gt;       Lewis     &lt;NA&gt;   1868-09-22
##  6       80 house   G000017  James     A.         Gallagher &lt;NA&gt;   1869-01-16
##  7       80 house   W000265  Richard   Joseph     Welch     &lt;NA&gt;   1869-02-13
##  8       80 house   B000565  Sol       &lt;NA&gt;       Bloom     &lt;NA&gt;   1870-03-09
##  9       80 house   H000943  Merlin    &lt;NA&gt;       Hull      &lt;NA&gt;   1870-12-18
## 10       80 house   G000169  Charles   Laceille   Gifford   &lt;NA&gt;   1871-03-15
## # … with 18,625 more rows, and 9 more variables: state &lt;chr&gt;, party &lt;chr&gt;,
## #   incumbent &lt;lgl&gt;, termstart &lt;date&gt;, age &lt;dbl&gt;, democrat &lt;dbl&gt;,
## #   num_democrat &lt;dbl&gt;, total &lt;int&gt;, prop_democrat &lt;dbl&gt;</code></pre>
</div>
<div id="useful-summary-functions" class="section level3">
<h3>Useful summary functions</h3>
<p>There are many useful summary functions, many of which we will explore in more detail in week 4 of the course during exploratory data analysis (EDA). However, I want to show a few here with the <code>summarise</code> function to ease you in. Suppose for instance we were interested in the knowing the youngest and oldest member of congress for each congress. There are actually two ways of doing this, one is using the <code>min</code> and <code>max</code> functions on the grouped data.</p>
<pre class="r"><code>summarise(congress_grp,
          youngest = min(age),
          oldest = max(age)
)</code></pre>
<pre><code>## # A tibble: 34 x 3
##    congress youngest oldest
##  *    &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1       80     25.9   85.9
##  2       81     27.2   85.2
##  3       82     27.9   87.2
##  4       83     26.7   85.3
##  5       84     28.5   87.3
##  6       85     30.5   89.3
##  7       86     31     91.3
##  8       87     28.9   86  
##  9       88     29     85.3
## 10       89     25     87.3
## # … with 24 more rows</code></pre>
<p>This could also be done by using the <code>first</code> and <code>last</code> functions after arranging the data:</p>
<pre class="r"><code>summarise(arrange(congress_grp, age),
          youngest = first(age),
          oldest = last(age)
)</code></pre>
<pre><code>## # A tibble: 34 x 3
##    congress youngest oldest
##       &lt;int&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1       80     25.9   85.9
##  2       81     27.2   85.2
##  3       82     27.9   87.2
##  4       83     26.7   85.3
##  5       84     28.5   87.3
##  6       85     30.5   89.3
##  7       86     31     91.3
##  8       87     28.9   86  
##  9       88     29     85.3
## 10       89     25     87.3
## # … with 24 more rows</code></pre>
<p>This goes to show that there are commonly many different ways to calculate descriptive statistics. I would argue two strong virtues when writing code is to make it as clear, expressive, and ensure accuracy. Speed and grace in writing code can come later.</p>
<div id="exercises-4" class="section level4">
<h4>Exercises</h4>
<ol style="list-style-type: decimal">
<li>For each congress, calculate a summary using the following command: <code>n_distinct(state)</code>. What does this value return?</li>
<li>What happens when you use a logical expression within a <code>sum</code> function call? For example, what do you get in a summarise when you do: <code>sum(age &gt; 75)</code>?</li>
<li>What happens when you try to use <code>sum</code> or <code>mean</code> on the variable incumbent?</li>
</ol>
</div>
</div>
</div>
<div id="chaining-together-multiple-operations" class="section level2">
<h2>Chaining together multiple operations</h2>
<p>Now that you have seen all of the basic <code>dplyr</code> data manipulation verbs, it is useful to chain these together to create more complex operations. So far, I have shown you how to do it by saving intermediate steps, for example, saving the grouped data after using the <code>group_by</code> function. In many instances, these intermediate steps are not useful to us. In these cases you can chain operations together.</p>
<p>Suppose we are interested in calculating the proportion of democrats for each chamber of congress, but only since the 100th congress? There are two ways to do this, the difficult to read and the easier to read. I first shown the difficult to read.</p>
<pre class="r"><code>summarise(
  group_by(
    mutate(
      filter(
        congress_age, congress &gt;= 100
      ), 
      democrat = ifelse(party == &#39;D&#39;, 1, 0)
    ),
    congress, chamber
  ),
  num_democrat = sum(democrat),
  total = n(),
  prop_democrat = num_democrat / total
)</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;congress&#39;. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 28 x 5
## # Groups:   congress [14]
##    congress chamber num_democrat total prop_democrat
##       &lt;int&gt; &lt;chr&gt;          &lt;dbl&gt; &lt;int&gt;         &lt;dbl&gt;
##  1      100 house            263   443         0.594
##  2      100 senate            55   101         0.545
##  3      101 house            266   445         0.598
##  4      101 senate            56   101         0.554
##  5      102 house            272   443         0.614
##  6      102 senate            59   104         0.567
##  7      103 house            261   443         0.589
##  8      103 senate            58   105         0.552
##  9      104 house            206   441         0.467
## 10      104 senate            47   103         0.456
## # … with 18 more rows</code></pre>
<p>How difficult do you find the code above to read? This is valid R code, but the first operation done is nested in the middle (it is the <code>filter</code> function that is run first). This makes for difficult code to debug and write in my opinion. In my opinion, the better way to write code is through the pipe operator, <code>%&gt;%</code>. The same code above can be achieved with the following much easier to read code:</p>
<pre class="r"><code>congress_age %&gt;%
  filter(congress &gt;= 100) %&gt;%
  mutate(democrat = ifelse(party == &#39;D&#39;, 1, 0)) %&gt;%
  group_by(congress, chamber) %&gt;%
  summarise(
    num_democrat = sum(democrat),
    total = n(),
    prop_democrat = num_democrat / total
  )</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;congress&#39;. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 28 x 5
## # Groups:   congress [14]
##    congress chamber num_democrat total prop_democrat
##       &lt;int&gt; &lt;chr&gt;          &lt;dbl&gt; &lt;int&gt;         &lt;dbl&gt;
##  1      100 house            263   443         0.594
##  2      100 senate            55   101         0.545
##  3      101 house            266   445         0.598
##  4      101 senate            56   101         0.554
##  5      102 house            272   443         0.614
##  6      102 senate            59   104         0.567
##  7      103 house            261   443         0.589
##  8      103 senate            58   105         0.552
##  9      104 house            206   441         0.467
## 10      104 senate            47   103         0.456
## # … with 18 more rows</code></pre>
<p>The pipe allows for more readable code by humans and progresses from top to bottom, left to right. The best word to substitute when translating the <code>%&gt;%</code> code above is ‘then’. So the code above says, using the <code>congress_age</code> data, then <code>filter</code>, then <code>mutate</code>, then <code>group_by</code>, then <code>summarise</code>.</p>
<p>This is much easier to read and follow the chain of commands. I highly recommend using the pipe in your code. For more details on what is actually happening, the R for Data Science book has a good explanation in Section 5.6.1.</p>
<div id="exercises-5" class="section level4">
<h4>Exercises</h4>
<ol style="list-style-type: decimal">
<li>Look at the following nested code and determine what is being done. Then translate this code to use the pipe operator.</li>
</ol>
<pre class="r"><code>summarise(
  group_by(
    mutate(
      filter(
        diamonds, 
        color %in% c(&#39;D&#39;, &#39;E&#39;, &#39;F&#39;) &amp; cut %in% c(&#39;Fair&#39;, &#39;Good&#39;, &#39;Very Good&#39;)
      ),
      f_color = ifelse(color == &#39;F&#39;, 1, 0),
      vg_cut = ifelse(cut == &#39;Very Good&#39;, 1, 0)
    ),
    clarity
  ),
  avg = mean(carat),
  sd = sd(carat),
  avg_p = mean(price),
  num = n(),
  summary_f_color = mean(f_color),
  summary_vg_cut = mean(vg_cut)
)</code></pre>
</div>
</div>

          </div>

          



          
          
          <div class="article-widget">
            
<div class="post-nav">
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Previous</div>
    <a href="/rcode/graphics-tips/" rel="next">Graphics Tips</a>
  </div>
  
  
  
  <div class="post-nav-item">
    <div class="meta-nav">Next</div>
    <a href="/rcode/r_scripts/" rel="prev">R Scripts</a>
  </div>
  
</div>

          </div>
          
        </div>

        <div class="body-footer">
          <p>Last updated on Feb 8, 2021</p>

          



          




          


        </div>

      </article>

      <footer class="site-footer">
  

  <p class="powered-by">
    
  </p>

  
  






  <p class="powered-by">
    
    
    
    Published with
    <a href="https://wowchemy.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Wowchemy</a>  —
    the free, <a href="https://github.com/wowchemy/wowchemy-hugo-modules" target="_blank" rel="noopener">
    open source</a> website builder that empowers creators.
    
  </p>
</footer>


    </main>
  </div>
</div>

  </div>

  <div class="page-footer">
    
    
  </div>

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/highlight.min.js" integrity="sha512-TDKKr+IvoqZnPzc3l35hdjpHD0m+b2EC2SrLEgKDRWpxf2rFCxemkgvJ5kfU48ip+Y+m2XVKyOCD85ybtlZDmw==" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/r.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.js" integrity="sha512-SeiQaaDh73yrb56sTW/RgVdi/mMqNeM2oBwubFHagc5BkixSpP1fvqF47mKzPGWYSSy4RwbBunrJBQ4Co8fRWA==" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'event' : "Events",
        'slides' : "Slides"
        };
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.2.2/anchor.min.js" integrity="sha512-I7w3ZdSFzw5j3jU3ZkNikBNeIrl3i+hEuEdwNmqUJvwNcaBUNcijnP2gd9DtGlgVYDplfjGoD8vTNsID+lCjqg==" crossorigin="anonymous"></script>
    <script>
      anchors.add();
    </script>
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
      
      
    
    
    <script src="/js/wowchemy.min.d4185df71ecf716f1c4e7ef5f3d4e2b8.js"></script>

    






</body>
</html>
